#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app

COPY . ./

RUN dotnet publish Aot.Hrms.Api.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/Aot.Hrms.Api/out .

ENTRYPOINT ["dotnet", "Aot.Hrms.Api.dll"]
