version: '3.4'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'aotdb'
      MYSQL_USER: 'aotuser'
      MYSQL_PASSWORD: 'q1w2e3'
      MYSQL_ROOT_PASSWORD: 'q1w2e3'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  aot.hrms.api:
    image: ${DOCKER_REGISTRY-}aothrmsapi
    build:
      context: .
      dockerfile: Aot.Hrms.Api/Dockerfile
    depends_on:
      - db
    ports:
      - '61653:80'
    expose:
      - '61653'
  aot.hrms.web:
    image: ${DOCKER_REGISTRY-}aothrmsweb
    build: ./Aot.Hrms.Web
    depends_on:
      - aot.hrms.api
    volumes:
      - './Aot.Hrms.Web:/usr/src/app' 
    ports: 
      - '4200:4200'
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
volumes:
  my-db: